### ISSUE TITLE
Logout page

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#127]
When user clicks 'Logout' while in the bibliographic editor, they will land on the logout page. See prototype: https://invis.io/5YNLDND63KF#/325884283_Logout

**Comment by michelleif** [comment]
test what happens now when user logs out

**Comment by michelleif** [comment]
Right now there is no "log out" option in the Linked Data Editor, only on the homepage. This is fine by me. Checking to see if this is ok technically. If so let's close this and I'll make a note in the documentation that says "to log out, go to the home page" (doesn't really matter since it logs you out when you close the browser window anyway.
