### ISSUE TITLE
Evaluate Trellis as LDP Component for Sinopia Server

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#129]

**Comment by cmh2166** [comment]
https://github.com/trellis-ldp

**Comment by jmartin-sul** [comment]
had a short meeting w/ @cmh2166 and @jermnelson to discuss figuring out whether trellis fits our needs.  questions christina has:
[ ] state of the codebase, dev practices:  adequately tested, well documented, well laid out, well maintained, in active use/development?
[ ] what does deployment mean?  expects a lot of infrastructure?  production ready release expects maybe a CentOS env running a suite of services (kafka topic, RDBMS or triplestore, etc)?
[ ] should have deployment patterns/scripts to spin up.  how reasonable are they, how reasonable is AWS deployment?  would be great to keep it in AWS, though we might be willing to do on prem if needed.
[ ] dockerized versions of dependencies from the trellis people.  how usable are they at present?
[ ] how easy is it to add functionality, how extensible is it?
  [ ] what is it missing that we need, what does it have that we don't need?
[ ] comes with a "read-only triplestore" as a "sidecar", implemented on camel?
[ ] last thing to investigate:  they have an AWS version in progress, what's the state of it?

@cmh2166, correct me if i got any of that wrong.

**Comment by cmh2166** [comment]
Done, see: https://github.com/LD4P/sinopia_server/wiki/Draft-Notes-for-Sinopia-Server-API-Spec

**Comment by acoburn** [comment]
@cmh2166 just an FYI, since I see that you're doing a lot of work with JSON-LD. Trellis supports custom JSON-LD profiles/contexts in responses. So, for instance, if you want a compact JSON-LD response using the Web Annotation `@context`, here's your request:

`curl -i http://localhost:8080/resource -H"Accept: application/ld+json; profile=\"http://www.w3.org/ns/anno.jsonld\""`

Because this is (potentially) a security issue -- letting clients download arbitrary web resources -- there is a whitelist in the configuration under

```yaml
jsonld:
  contextWhitelist:
    - http://www.w3.org/ns/anno.jsonld
```

You can add as many contexts as you like, or even open up an entire domain as "trusted". These remote contexts also get cached internally to help speed things up.

**Comment by cmh2166** [comment]
@acoburn thanks for this! i'll try to break up our questions & such so we can get them here and ping you (+ the trellis google groups) more

**Comment by acoburn** [comment]
@cmh2166 that sounds great! I noticed you had a question about provenance data (who changes what resources and when) -- each resource has a full audit log that you can view with Prefer headers. Documentation is here: https://github.com/trellis-ldp/trellis/wiki/Resource-Provenance--(Audit)

The audit trail doesn't tell you exactly which triples where changed, but you can establish that by combining the data with the Memento representations (if you wanted to know which particular triples were modified by a certain user at a certain point in time).
