### ISSUE TITLE
React Tutorial

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#197]
Self-paced learning React by going through the [React Tutorial: Intro to React](https://reactjs.org/tutorial/tutorial.html) 

- [x] @jmartin-sul 
- [x] @ndushay 
- [x] @mjgiarlo

Blocks #198

**Comment by jmartin-sul** [comment]
ah, so it turns out the one i've read through is the counterpart to the practical tutorial linked in the description:  https://reactjs.org/docs/hello-world.html

per the docs at https://reactjs.org/docs/getting-started.html (which links to both tutorials):
> People come to React from different backgrounds and with different learning styles. Whether you prefer a more theoretical or a practical approach, we hope you’ll find this section helpful.
> 
>     If you prefer to learn by doing, start with our practical tutorial  _(linked in description)_.
>     If you prefer to learn concepts step by step, start with our guide to main concepts _(linked in this comment)_.

each intro also says at the top that users might find the two "complementary to each other".

so, i'll still try to do the tutorial linked in the description, and won't check myself off of the list yet.  but i might be a little more inclined to skim it, and do the

**Comment by ndushay** [comment]
@mjgiarlo too?
