### ISSUE TITLE
Sinopia Unexpected Closing of Linked Data Editor

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia#227]
In stage... Open Resource Template: sinopia:resourceTemplate:bf2:Monograph:Work  Under the "Has BIBFRAME Instance" box select "Has Item" -- system boots the user out.  This should open the Item resource template properties.  I've encountered the same problem with other similarly structured Work, Instance, Item profiles.  It's also strange because the sinopia:resourceTemplate:bf2:Monograph:Item seems to work fine when open in the editor directly.

**Comment by jermnelson** [comment]
Hi @mmcgee, I believe this is now fixed in Stage if you want to test again.
thanks! If you're satisfied with the result, we can close this issue. Sorry for not responding sooner; typically the Linked Data Editor bugs are reported directly as issues in this Github repository https://github.com/LD4P/sinopia_editor/issues.

**Comment by mmcgee** [comment]
Thanks @jermnelson this one appears to be fixed

**Comment by jermnelson** [comment]
👍
