### ISSUE TITLE
Move from embedding resources to linking resources

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia#249]
In particular, the appropriate resource templates should be changed so that:
* Bibframe instances link to bibframe works
* Bibframe works link to bibframe instances

Within the Sinopia editor, this means that the embedded resource template would be replaced by a Sinopia lookup component.

The motivations for this are:
* Support the re-use of instance / works (since an embedded resource is not re-usable, as it does not have a URI). Thus, if a user is describing an instance and that instance requires a new work, the user will create the new work and link to it in the instance. If in the future another instance of that work is required, it can be linked to the work as well.
* Provide a "boundary" around records. The current approach allows infinite recursion (as an instance can include a work which can include instances, ad infinitum). Thus, the boundary of a record becomes when a URI or literal is encountered; records don't recurse.

**Comment by michelleif** [comment]
another advantage of linked vs embedded is that it gives more flexibility for customization: from slack #profiles channel aug 23, 2019:
"...if you want to set library-specific defaults in an Item RT you also have to copy and have your own set of related Work & Instance templates... so... what if the local Item RT was a standalone template and instead of embedding it directly into the Instance RT, you instead made corresponding bf:hasItem, bf:itemOf relationships.  wouldn't that allow everyone to use the same base Work and Instance templates while still being able to use a local Item template?  you might have to assert the relationships each way from both the Instance and the Item, and we'd need a way to look-up Items (Not sure what you might index)  but shouldn't that work without the need to proliferate institutional RTs for Works and Instances?  Should this at least be the model for the shared starter RTs?"

**Comment by michelleif** [comment]
another comment about nesting from slack #profiles channel aug 29, 2019:
"Looking as the base ld4p RTs -- Is it necessary to have reciprocal relationships in Sinopia profiles?  e.g., If you are starting in a Work RT, e.g., mono Work, it has property bf:hasInstance which opens the Instance RT where the first property circles right back to the Work RT with bf:instanceOf,  ad infinitum.  Similar circular issue with the Instance RT which starts with bf:instanceof opening the Work RT which includes bf:hasInstance which opens the Instance RT.  It creates a confusing and redundant UI experience."

**Comment by michelleif** [comment]
this is not a development ticket. this is a reminder to advise Profile Creators that less embedding will have advantages.

**Comment by michelleif** [comment]
discussion is ongoing in profiles group. remains to be seen what kind of additional Sinopia features might be requested to support a more un-nested set up. no development work required for now so I'm closing this ticket.
