### ISSUE TITLE
Clean up the panel UI

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#261]
Now that we know what all the requirements are for the panel UI, clean up the existing UI so that it follows UI patterns that are familiar to users. 
![image](https://user-images.githubusercontent.com/42216982/64575282-d3140280-d327-11e9-8503-a2be5832cc39.png)

**Comment by justinlittman** [comment]
Questions @astridu:
1. This shows moving the open more info icon as being before the field title. What should happen when there is also a toggle icon. For example, for quarternary field 5, where would the more info icon go?
2. For add and add another, I'm not clear how this is supposed to differ from existing functionality? (That is, is it just a UI change or are there functionality differences.) Can you provide some examples with actual field values and/or that detail individual user interactions?
3. For expanding the section, but not adding to RDF: This is problematic because of defaults / required values. How would this work? 

Will set up meeting to discuss, but wanted to document questions.

**Comment by michelleif** [comment]
one more question for our discussion @astridu 
--for repeatable literal fields, does this mean "add another" (value) will create a new box? or they will still enter the second value in the first box? we need to fix #1285 (make UI for non-repeatable lookup fields intuitive) where one of the problems is that non-repeatable values were not being shown in blue after being entered, like repeatable values are. (same for lookup and URI fields too). will this design fix that problem?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/66604889-e05d2080-eb63-11e9-8eaa-c53e747cc6b1.png)
Some notes about the design:
1. The 'Sort by' drop down allows user to sort by title, date, relevance.
2. There is a secondary selection user makes when they pick 'Sort by'. 
a. For title: Ascending, descending
b. For date: Oldest on top, newest on top
c. For Relevance: Most relevant, least relevant (or you can skip this one if you think everyone will just pick most relevant)

**Comment by astridu** [comment]
_> --for repeatable literal fields, does this mean "add another" (value) will create a new box? or they will still enter the second value in the first box? we need to fix #1285 (make UI for non-repeatable lookup fields intuitive) where one of the problems is that non-repeatable values were not being shown in blue after being entered, like repeatable values are. (same for lookup and URI fields too). will this design fix that problem?_
Yes, this design will create a new box that the user will type in, hit return, then that value becomes a link. This link can be clicked on to edit the value. The link will also come with a trash can so user can delete it. This will fix the non-repeatable field issue because it will not have an '+Add' link once user has entered in a value indicating that it is a non-repeatable field, but it will have the link (to edit) and trash can (to delete).

**Comment by michelleif** [comment]
moved Astrid's design for advanced Sinopia search / sorting to #90

**Comment by michelleif** [comment]
@astridu can we walk through some screens of how it would look before and after data is entered? I am confused by the part where an entered value becomes a clickable link, because what about entered URIs, which are supposed to become clickable links to the URI? if clicking is for editing, what happens to clickable URIs?

**Comment by michelleif** [comment]
completed what was planned for this Work Cycle; adding "future" label to come back to the rest

**Comment by michelleif** [comment]
@astridu could you review this and see which things we didn't implement that are still desired by catalogers, and create a new ticket(s) for those things, if no ticket exists?

**Comment by astridu** [comment]
@michelleif Sure, you can close this ticket. I consider this work completed, and I'll submit new tickets for any changes to the UI separately.
