### ISSUE TITLE
Publish the Sinopia vocabulary

### ISSUE THREAD

**Issue by younnoh** [LD4P/sinopia#277]

**Comment by jermnelson** [comment]
All resource templates, including their identifiers, are indexed in Sinopia. Sinopia currently does not save any profile identifiers that contain resource templates.

**Comment by michelleif** [comment]
we should make the Sinopia property de-referencable: http://sinopia.io/vocabulary/hasResourceTemplate
are there any other classes or properties in Sinopia namespace? @jermnelson

**Comment by michelleif** [comment]
"publishing the sinopia.io/vocabulary": this is newly relevant and required now that templates are handled as resources and the sinopia.io/vocabulary define those templates

re 2nd part of original request: "consider maintaining a registry of resource template identifiers": would need a use case for this, since you can browse / search all the template in Sinopia already

**Comment by briesenberg07** [comment]
Hi:
I'm still not able to dereference Sinopia vocab IRIs. 
I wanted to check because I see that this issue is closed, the referenced pull request has been merged, etc.
Are there any updates regarding publishing the vocab? Perhaps this issue has moved elsewhere and I just haven't seen it, etc.? Thank you!

![image](https://user-images.githubusercontent.com/27664966/95145538-57ee6d00-0730-11eb-9640-a2364446c543.png)

**Comment by michelleif** [comment]
we published to stage so stage.sinopia.io/vocabulary and will publish to sinopia.io this week. will reopen this until it's published on production.

**Comment by briesenberg07** [comment]
Thank you for the update @michelleif ! Apologies if I missed this info elsewhere!

**Comment by jermnelson** [comment]
@briesenberg07 the Sinopia vocabulary is now live at https://sinopia.io/vocabulary/ so closing this issue. Let us know if you have any questions or comments.

Thanks!

**Comment by briesenberg07** [comment]
🥳 It's dereferencing, and it looks great! 🎉 
Thanks much @jermnelson , @justinlittman , et al !
