### ISSUE TITLE
QA Lookup Modal

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#292]
From Lynette's ticket: 
Expected user actions

user selects cache authority with minimal set of subauths selected
user types search term and hits Lookup button
results are populated in a table with context in different columns
if acceptable result NOT found, select more or other subauths
if acceptable result NOT found, select direct authority instead of cached
user clicks a result and is returned to Sinopia edit page with field populated with the result
This allows one field to support multiple authorities and subauthorities while at the same time allowing the user more control over the process.

Mockup: Personal Name (LoC) - Lookup with Context and Multiple Authorities (original mockup from LD4P Labs)

Use Case: Select Multiple Results
Allows a user to select multiple values from a single set of search results.

Expected user actions

user types search term and hits Lookup button
results are populated in a table with context in different columns
user checks multiple results
user clicks Save and is returned to Sinopia edit page with field populated multiple times with each selected result
Mockup: Genre/Form (LoC) (original mockup from LD4P Labs)

Use Case: Select Multiple Results from Primary Result and/or Context
This is an extension of the last example to include selection of results from the context for a result. This is especially useful for hierarchical vocabularies with broader and narrower terms.

Expected user actions

user types search term and hits Lookup button
results are populated in a table with context in different columns
user checks multiple results from the primary column and/or preconfigured context columns that can also serve as the result (QA already includes which columns can be selected)
user clicks Save and is returned to Sinopia edit page with field populated multiple times with each selected result
Mockup: Genre/Form (LoC) (original mockup from LD4P Labs) - same as last example

Additional Features
A Lookup UI could also support:

pagination to get more results
clicking on a hierarchical term performs a lookup on that term
control lookup process by selecting left anchored search or key word search

**Comment by jermnelson** [comment]
![image.png](https://images.zenhubusercontent.com/5d89240e64a0e5000151e46b/c950f77b-5182-4084-a78c-4dbe99c18930)

**Comment by jermnelson** [comment]
Part of the work for this epic is seeing how we can consolidate the functionality of the following Sinopia components to use the same `InputLookupModal`:
-  InputLookupQA - **Done** already uses the Modal 
-  InputListLOC - Currently uses `Typeahead` component for displaying a value list. We will see if QA could add these vocabularies so that we could depreciate this component and just use the `InputLookupQA` both QA and LOC. I'll bring this up at the 9/23 Sinopia/QA meeting.
- InputLookupSinopia - **Done** already uses the Modal.  

Related to this is to investigate if we can remove all other uses of the `Typeahead` in ticket [2524](https://github.com/LD4P/sinopia_editor/issues/2524)

**Comment by michelleif** [comment]
@jermnelson what remains to be done from this ticket?

**Comment by jermnelson** [comment]
Closing; I think the work has been accomplished.
