### ISSUE TITLE
Copy an existing form (so you can create a new form)

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#35]
A24: Ability to Copy an existing form (so you can create a new form).

Wherever forms are stored, can either access & duplicate manually, or load in profile editor & duplicate to create a new form.

**Comment by michelleif** [comment]
if you copy someone else's form and make changes, you shouldn't be able to overwrite their form in the Editor, but you can add your new form to Editor as a different form

**Comment by michelleif** [comment]
when a profile is loaded into Editor, could we have a check to see if this profile has the same ID or Title as one that already exists, and if it does, ask them if they want to give it a new name? (not talking here about preventing overwriting, since you can only overwrite your own, just talking about avoiding confusion from having multiple profiles with same Title)

**Comment by michelleif** [comment]
this ticket is conflating the creation of a new form based on a copy, and the updating of an existing form.
